name: Cypress-API-tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install dependencies
      run: npm install
      working-directory: ./cypress/

    - name: Run ESLint
      run: npm run lint:check
      working-directory: ./cypress/cypress/

    - name: Run tests
      run: npm run cypress:run
      working-directory: ./cypress/
